spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: msvc-auth-register
          uri: lb://msvc-auth-register
          predicates:
            - Path=/auth/**
            
        - id: msvc-auth-admin
          uri: lb://msvc-auth-register
          predicates:
            - Path=/user/v1/**
          filters:
            - name: JwtHeader
              args:
                requireValidToken: true
            
        - id: msvc-request-medicine
          uri: lb://msvc-request-medicine
          predicates:
            - Path=/requestMedicine/**, /medicine/**
          filters:
            - name: JwtHeader
              args:
                requireValidToken: true
                



# Configuración del JWT
jwt:
  secret:
    key: ZorKMdMELhJignPapUu+tm+yrGuKNi4u6JyJ94n26v5K+I7QehQ7gSGyDbJJ+Q2j

server:
  port: 8080
