spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/request
    username: admin
    password: Root@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  main:
    allow-bean-definition-overriding: true

server:
  port: 9393

springdoc:
  swagger-ui:
    path: /medicine/swagger-ui.html
  api-docs:
    path: /medicine/api-docs
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
clients:
  users:
    uri: lb://msvc-auth-register
