spring:
 datasource:
   url: jdbc:postgresql://localhost:5433/users
   username: admin
   password: Root@123
   driver-class-name: org.postgresql.Driver
 jpa:
   hibernate:
     ddl-auto: update
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 main:
   allow-bean-definition-overriding: true
server:
 Port: 9292

springdoc:
  swagger-ui:
    path: /auth/swagger-ui.html
  api-docs:
    path: /auth/api-docs
    enabled: true
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
 instance:
  instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
jwt:
 secret:
  key: ZorKMdMELhJignPapUu+tm+yrGuKNi4u6JyJ94n26v5K+I7QehQ7gSGyDbJJ+Q2j
